language: node_js
branches:
  only:
  - master
  - api-v2
cache:
  directories:
  - node_modules
notifications:
  slack:
    rooms:
      secure: X+LogZiKFDkcjG9MZb6o0IsVL9d56CD41auvw0yzmYyzfVbR4AYNFUh4ebTGc3DM8iFAXbjLV8Jlg7ADyj6KyxHHr63XRzruN374nouN7EHgaxF6MKLAMTxxYasn1x9XXUNrXDDhDS3Em/+TbQs3lenB1YfKjikOavNBC10bdcA=
    on_success: change
    on_failure: always
node_js:
- 8.10.0
script:
- npm run build
after_success:
- npm run deploy-docs
